#include <algorithm>
#include <cstddef>
#include <print>
#include <string>
#include <vector>

#include <gnuradio-4.0/Block.hpp>
#include <gnuradio-4.0/BlockRegistry.hpp>
#include <minimal_blocklib/Gain.hpp>

#include <gnuradio-4.0/MinimalBlockLib.hpp> // generated by gr_add_block_library

// Explicit initialization is the contract for a linked block library, static or shared. A shared
// library that nothing references is not recorded in DT_NEEDED under the linker's default
// --as-needed, so it is never loaded and its static initializers never run; registration that
// relies on them is not portable. Calling the generated initializer registers the blocks, and it
// also keeps a static library's objects from being discarded.
int main() {
    gr::minimal_blocklib::Gain<float> direct;
    direct.gain = 2.0F;
    if (direct.processOne(3.0F) != 6.0F) {
        std::println(stderr, "the directly instantiated block did not compute");
        return 1;
    }

    // The return value is deliberately not asserted on. A generated unit initializer counts the
    // insertBlockFactory() calls that returned false, and BlockRegistry::insert() returns false for
    // a key that was already present, so re-registering an already-registered block is reported as
    // a failure. The generated definition unit also registers into globalBlockRegistry() from a
    // static initializer, so an explicit call into that registry reports every block as failed. The
    // generated module function then applies ! to that count, so its result is neither a count of
    // blocks nor a count of failures. The check below is the contract that matters: after
    // initialization the registry can find the block and construct it.
    gr::BlockRegistry& registry   = gr::globalBlockRegistry();
    const std::size_t  initResult = gr::blocklib::initMinimalBlockLib(registry);

    const std::vector<std::string> keys = registry.keys();
    const auto                     gain = std::ranges::find_if(keys, [](const std::string& key) { return key.contains("Gain"); });
    if (gain == keys.end()) {
        std::println(stderr, "the registry has {} entries and none of them is the Gain block", keys.size());
        return 3;
    }

    const std::unique_ptr<gr::BlockModel> block = registry.create(*gain, {});
    if (!block) {
        std::println(stderr, "the registry knows '{}' but could not construct it", *gain);
        return 4;
    }

    std::println("constructed '{}' through the registry after explicit initialisation (init returned {})", *gain, initResult);
    return 0;
}
