#ifndef GNURADIO_PLUGIN_H
#define GNURADIO_PLUGIN_H

#include <span>
#include <string>
#include <string_view>

#include <dlfcn.h>

#include "BlockRegistry.hpp"

#include <gnuradio-4.0/Export.hpp>
#include <gnuradio-4.0/PluginMetadata.hpp>

using namespace std::string_literals;
using namespace std::string_view_literals;

// The version of the plugin interface, raised by every change to the layout of a type that crosses the plugin
// boundary: `gr_plugin_base` itself, and the `BlockModel` and `SchedulerModel` interfaces whose objects a plugin
// hands back. A plugin records the version it was compiled against and a host loads only a plugin whose version
// equals its own, because a virtual call through a mismatched interface reaches the wrong function.
#define GR_PLUGIN_CURRENT_ABI_VERSION 3

class GNURADIO_EXPORT gr_plugin_base {
public:
    gr_plugin_metadata metadata;

    virtual ~gr_plugin_base();

    virtual std::uint8_t abiVersion() const = 0;

    virtual std::vector<std::string>        availableBlocks() const                                            = 0;
    virtual std::unique_ptr<gr::BlockModel> createBlock(std::string_view name, const gr::property_map& params) = 0;

    virtual std::vector<std::string>            availableSchedulers() const                                           = 0;
    virtual std::unique_ptr<gr::SchedulerModel> createScheduler(std::string_view name, const gr::property_map& param) = 0;

    // an entry appends here, so that abiVersion() keeps the slot a plugin built against an older ABI gave it, and
    // carries a name of its own, so that an implementor overriding one of the two does not hide the other
    virtual std::vector<gr::block::Version> blockVersions(std::string_view name) const                                                           = 0;
    virtual std::unique_ptr<gr::BlockModel> createPinnedBlock(std::string_view name, gr::block::Version version, const gr::property_map& params) = 0;
};

namespace gr {
template<std::uint8_t ABI_VERSION = GR_PLUGIN_CURRENT_ABI_VERSION>
class plugin : public gr_plugin_base {
private:
    gr::BlockRegistry     registry;
    gr::SchedulerRegistry schedulerRegistry;

public:
    plugin() {}

    std::uint8_t abiVersion() const override { return ABI_VERSION; }

    std::vector<std::string>        availableBlocks() const override { return registry.keys(); }
    std::unique_ptr<gr::BlockModel> createBlock(std::string_view name, const property_map& params) override { return registry.create(name, params); }

    std::vector<std::string>            availableSchedulers() const override { return schedulerRegistry.keys(); }
    std::unique_ptr<gr::SchedulerModel> createScheduler(std::string_view name, const property_map& params) override { return schedulerRegistry.create(name, params); }

    std::vector<block::Version>     blockVersions(std::string_view name) const override { return registry.versions(name); }
    std::unique_ptr<gr::BlockModel> createPinnedBlock(std::string_view name, block::Version version, const property_map& params) override { return registry.create(name, version, params); }

    operator gr::BlockRegistry&() { return registry; }
    operator gr::SchedulerRegistry&() { return schedulerRegistry; }
};

} // namespace gr

/*
 * Defines a plugin - creates the plugin meta-data and creates
 * a block registry (grPluginInstance()) for the plugin.
 *
 * Arguments:
 *  - plugin name
 *  - author
 *  - license of the plugin
 *  - plugin version
 *
 * Example usage:
 *     GR_PLUGIN("Good Base Plugin", "Unknown", "MIT", "v1")
 */
#define GR_PLUGIN(Name, Author, License, Version)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
    gr::plugin<>& grPluginInstance() {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
        static gr::plugin<> instance = [] {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \
            gr::plugin<> result;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
            result.metadata = gr_plugin_metadata{.plugin_name = Name, .plugin_author = Author, .plugin_license = License, .plugin_version = Version};                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
            return result;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
        }();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   \
        return instance;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
    gr::BlockRegistry& grPluginBlockRegistry() { return static_cast<gr::BlockRegistry&>(grPluginInstance()); }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
    extern "C" {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
    void GNURADIO_EXPORT gr_plugin_make(gr_plugin_base** plugin) { *plugin = &grPluginInstance(); }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
    void GNURADIO_EXPORT gr_plugin_free(gr_plugin_base*) {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \
    }

#endif // include guard
